name: CI App

on:
  push:
    branches:
      - main
    paths:
      - 'Application/*'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: "Application"

      - name: Download docker
        run: |
          #!/bin/bash
          sudo apt update -y
          sudo apt install -y docker
          sudo service docker start

      - name: Build
        run: docker build -t ${DOCKER_IMAGE}  .
        env:
          DOCKER_IMAGE : ${{secret.DOCKER_IMAGE}}

      
      - name: Login to DockerHub
        run: docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
        env:
          DOCKER_HUB_USERNAME : ${{secret.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_PASSWORD : ${{secret.DOCKER__HUB_PASSWORD}}


      - name: Publish
        run: docker push ${DOCKER_IMAGE}
        env:
          DOCKER_IMAGE : ${{secret.DOCKER_IMAGE}}

      - name: Logout from DockerHub
        run: docker logout
      