name: clean-deployment

on:
  push:
    branches:
      - dev
    paths:
      - '**.tf'
  workflow_dispatch:

jobs:
  terraform:
    name: Clean Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.9.1'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan #This for restoring the tfstate files.
        run: terraform plan
        env:
          TF_VAR_AWS_USER_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_USER_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        env:
          TF_VAR_AWS_USER_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_USER_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }}

