name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    TF_VAR_AWS_USER_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
    TF_VAR_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure
    if: contains(github.event.head_commit.message, 'deploy-infra')
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.9.1'
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Refresh
        run: terraform refresh

      - name: Terraform Validate #If the code is not valid. we won't continue to applying. a bit time save.
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply --auto-approve
